<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Presentation 5: Intro to Modelling in R – R for Data Science</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">R for Data Science</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Course Material</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../about_heads.html"> 
<span class="menu-text">About us</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../presentations/presentation1.html">Presentations</a></li><li class="breadcrumb-item"><a href="../presentations/presentation5.html">Presentation 5: Intro to Modelling in R</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../slides/R4datascience_slides.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Slides️</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Presentations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../presentations/presentation1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentation 1: Data Cleanup</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../presentations/presentation2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentation 2: Advanced Data Wrangling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../presentations/presentation3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentation 3: Exploratory Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../presentations/named_lists.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R Objects: Named Lists</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../presentations/presentation4_main_script.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentation 4: Scripting in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../presentations/presentation4_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Presentation 4, Functions: Scripting in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../presentations/presentation5.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Presentation 5: Intro to Modelling in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../presentations/s4_objects.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">R objects: S4 objects</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../data/data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Data️</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false">
 <span class="menu-text">Exercises</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../exercises/exercise0.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 0: R script and Quarto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../exercises/exercise1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 1: Data Cleanup</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../exercises/exercise2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 2: Advanced Data Wrangling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../exercises/exercise3A.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 3 A: Exploratory Data Analysis - Plotting</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../exercises/exercise3B.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 3 B: Exploratory Data Analysis - PCA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../exercises/exercise4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 4: Scripting in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../exercises/exercise5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 5: Modelling in R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../exercises/exercise6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 6: Understanding and improving an R script</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false">
 <span class="menu-text">Solutions</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../solutions/solution1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 1 - Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../solutions/solution2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 2 - Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../solutions/solution3A.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 3 A - Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../solutions/solution3B.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 3 B - Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../solutions/solution4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 4 - Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../solutions/solution4_functions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 4, Functions - Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../solutions/solution5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 5 - Solution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../solutions/solution6.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Exercise 6 - Solution</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false">
 <span class="menu-text">Cheat Sheets</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../CheatSheet/quartoCheatSheet.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quarto</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../CheatSheet/BaseRCheatSheet.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Base R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../CheatSheet/TidyverseCheatSheet.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Tidyverse</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../CheatSheet/ggplotCheatSheet.pdf" class="sidebar-item-text sidebar-link">
 <span class="menu-text">ggplot2</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#load-packages" id="toc-load-packages" class="nav-link active" data-scroll-target="#load-packages">Load packages</a></li>
  <li><a href="#load-data" id="toc-load-data" class="nav-link" data-scroll-target="#load-data">Load data</a></li>
  <li><a href="#linear-regression" id="toc-linear-regression" class="nav-link" data-scroll-target="#linear-regression">Linear Regression</a>
  <ul class="collapse">
  <li><a href="#split-data-into-training-and-test-set" id="toc-split-data-into-training-and-test-set" class="nav-link" data-scroll-target="#split-data-into-training-and-test-set">Split Data into Training and Test Set</a></li>
  <li><a href="#defining-the-model" id="toc-defining-the-model" class="nav-link" data-scroll-target="#defining-the-model">Defining the model</a></li>
  <li><a href="#modelling-results" id="toc-modelling-results" class="nav-link" data-scroll-target="#modelling-results">Modelling results</a></li>
  <li><a href="#model-interpretation" id="toc-model-interpretation" class="nav-link" data-scroll-target="#model-interpretation">Model interpretation</a></li>
  <li><a href="#model-performance" id="toc-model-performance" class="nav-link" data-scroll-target="#model-performance">Model performance</a></li>
  </ul></li>
  <li><a href="#regression-with-categorical-features" id="toc-regression-with-categorical-features" class="nav-link" data-scroll-target="#regression-with-categorical-features">Regression with categorical features</a></li>
  <li><a href="#classification" id="toc-classification" class="nav-link" data-scroll-target="#classification">Classification</a>
  <ul class="collapse">
  <li><a href="#training-and-test-set-with-class-data" id="toc-training-and-test-set-with-class-data" class="nav-link" data-scroll-target="#training-and-test-set-with-class-data">Training and Test set with class data</a></li>
  <li><a href="#logistic-regression-math" id="toc-logistic-regression-math" class="nav-link" data-scroll-target="#logistic-regression-math">Logistic regression: Math</a></li>
  <li><a href="#model-formulation-in-r" id="toc-model-formulation-in-r" class="nav-link" data-scroll-target="#model-formulation-in-r">Model formulation in R</a></li>
  <li><a href="#model-interpretation-1" id="toc-model-interpretation-1" class="nav-link" data-scroll-target="#model-interpretation-1">Model interpretation</a></li>
  <li><a href="#model-comparison" id="toc-model-comparison" class="nav-link" data-scroll-target="#model-comparison">Model comparison</a></li>
  </ul></li>
  <li><a href="#clustering" id="toc-clustering" class="nav-link" data-scroll-target="#clustering">Clustering</a>
  <ul class="collapse">
  <li><a href="#wine-dataset" id="toc-wine-dataset" class="nav-link" data-scroll-target="#wine-dataset">Wine dataset</a></li>
  <li><a href="#running-k-means" id="toc-running-k-means" class="nav-link" data-scroll-target="#running-k-means">Running k-means</a></li>
  <li><a href="#visualizing-k-means-results" id="toc-visualizing-k-means-results" class="nav-link" data-scroll-target="#visualizing-k-means-results">Visualizing k-means results</a></li>
  <li><a href="#optimal-number-of-clusters" id="toc-optimal-number-of-clusters" class="nav-link" data-scroll-target="#optimal-number-of-clusters">Optimal number of clusters</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../presentations/presentation1.html">Presentations</a></li><li class="breadcrumb-item"><a href="../presentations/presentation5.html">Presentation 5: Intro to Modelling in R</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Presentation 5: Intro to Modelling in R</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In this section we’ll look at how to define and fit a model in R.</p>
<section id="load-packages" class="level2">
<h2 class="anchored" data-anchor-id="load-packages">Load packages</h2>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(caTools)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ModelMetrics)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggfortify)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readxl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="load-data" class="level2">
<h2 class="anchored" data-anchor-id="load-data">Load data</h2>
<p>In order to focus on the technical aspects we’ll use a very simple toy dataset. It contains the number of cigarettes smoked per day and how long the person lived. It is inspired by <a href="https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2598467/">this paper</a> if you want to take a look.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df_smoke <span class="ot">&lt;-</span> <span class="fu">as_tibble</span>(<span class="fu">read.csv</span>(<span class="st">'../data/smoking_cat.csv'</span>))</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>df_smoke</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 100 × 3
   daily_cigarettes  life exercise
              &lt;int&gt; &lt;int&gt;    &lt;int&gt;
 1                7    76        0
 2               11    73        0
 3               27    72        1
 4               23    71        0
 5               13    74        0
 6               11    76        1
 7               20    71        0
 8                6    76        1
 9               23    72        1
10               32    70        2
# ℹ 90 more rows</code></pre>
</div>
</div>
<p>We will use this to perform a linear regression.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/lin_reg.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</section>
<section id="linear-regression" class="level2">
<h2 class="anchored" data-anchor-id="linear-regression">Linear Regression</h2>
<section id="split-data-into-training-and-test-set" class="level3">
<h3 class="anchored" data-anchor-id="split-data-into-training-and-test-set">Split Data into Training and Test Set</h3>
<p>First, we will split our data into a test and a training set. There are numerous ways to do this. We here show <code>sample_frac</code> from <code>dplyr</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed to ensure reproducibility</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co">#add an ID column to keep track of observations</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>df_smoke<span class="sc">$</span>ID <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df_smoke)</span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> df_smoke <span class="sc">%&gt;%</span> <span class="fu">sample_frac</span>(.<span class="dv">75</span>)</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 75</code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  daily_cigarettes  life exercise    ID
             &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;int&gt;
1               29    72        1    31
2               16    73        0    79
3                5    78        1    51
4                3    77        0    14
5                4    79        2    67
6               23    71        1    42</code></pre>
</div>
</div>
<p>As you can see, the ID’s in <code>train</code> are shuffled and it only has 75 rows since we asked for 75% of the data. Now all we have to do is identify the other 25%, i.e.&nbsp;the observations not in train. <code>dpylr</code> has a neat function called <code>anti_join</code> for that:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co">#from df_smoke remove what is in train by checking the ID column</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>test  <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(df_smoke, train, <span class="at">by =</span> <span class="st">'ID'</span>) </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="fu">nrow</span>(test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(test)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 4
  daily_cigarettes  life exercise    ID
             &lt;int&gt; &lt;int&gt;    &lt;int&gt; &lt;int&gt;
1                7    76        0     1
2               11    73        0     2
3               27    72        1     3
4               32    70        2    10
5                8    75        0    11
6               16    75        2    24</code></pre>
</div>
</div>
</section>
<section id="defining-the-model" class="level3">
<h3 class="anchored" data-anchor-id="defining-the-model">Defining the model</h3>
<p>As stated above, a linear regression model generally has the form of:</p>
<p><span class="math display">\[y=b_0+b_1*x_i\]</span></p>
<p>Where we refer to <span class="math inline">\(b_0\)</span> as the intercept and <span class="math inline">\(b_1\)</span> as the coefficient. There will typically be one coefficient for each predictor. The goal of modelling is to estimate the values of <span class="math inline">\(b_0\)</span> and all <span class="math inline">\(b_i\)</span>.</p>
<p>We need to tell R which of our variables is the outcome, <span class="math inline">\(y\)</span> and which predictors <span class="math inline">\(x_i\)</span> we want to include in the model. This is referred to in documentation as the model’s <strong>formula</strong>. Have a look:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#the formula is written like so:</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lm</span>(y <span class="sc">~</span> x_1 <span class="sc">+</span> x_2 <span class="sc">+</span> ...)</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co">#see the help</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>?lm</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In our case, <span class="math inline">\(y\)</span> is the number of years lived and we have a singular predictor <span class="math inline">\(x_1\)</span>, the number of cigarettes smoked per day. So that will be our model formulation:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co">#remember to select the training data subset we defined above! </span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(life <span class="sc">~</span> daily_cigarettes, <span class="at">data =</span> train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="modelling-results" class="level3">
<h3 class="anchored" data-anchor-id="modelling-results">Modelling results</h3>
<p>By calling <code>lm</code> we have already trained our model! The return of <code>lm()</code> is, just like the return of <code>prcomp()</code>, a named list.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">typeof</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "list"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">class</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "lm"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "coefficients"  "residuals"     "effects"       "rank"         
 [5] "fitted.values" "assign"        "qr"            "df.residual"  
 [9] "xlevels"       "call"          "terms"         "model"        </code></pre>
</div>
</div>
<p>Lets have a look at the results. The summary gives us a lot of information about the model we trained:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View model summary</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life ~ daily_cigarettes, data = train)

Residuals:
     Min       1Q   Median       3Q      Max 
-2.71479 -1.03035 -0.06517  0.82928  2.84669 

Coefficients:
                 Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      78.71479    0.26847  293.20   &lt;2e-16 ***
daily_cigarettes -0.28074    0.01351  -20.77   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.251 on 73 degrees of freedom
Multiple R-squared:  0.8553,    Adjusted R-squared:  0.8533 
F-statistic: 431.5 on 1 and 73 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>It beings with <strong>Call</strong> which displays the formula used to fit the model.</p>
<p>The <strong>Residuals</strong> section summarizes the distribution of the residuals, which is the difference between the actual observed <span class="math inline">\(y\)</span> values and the fitted <span class="math inline">\(y\)</span> values.</p>
<p>The <strong>Coefficients</strong> table shows the estimated values for each coefficient including the intercept, along with their standard errors, t-values, and p-values. These help to determine the significance of each predictor. Smaller p-values indicate stronger evidence against the null hypothesis that the true coefficient is zero.</p>
<p>In the bottom section we have some information about how well model fits the training data. The <strong>Residual Standard Error (RSE)</strong> provides a measure of accuracy as it represents the average size of the residuals. The <strong>R-squared</strong> value indicates the proportion of variance explained by the model, with the Adjusted R-squared accounting for the number of predictors to prevent overfitting. Finally, the <strong>F-statistic</strong> and its p-value test whether the model as a whole explains a significant portion of the variance in the response variable (the outcome <span class="math inline">\(y\)</span>).</p>
<p>Overall, the <code>summary</code> helps us to assess the model fit and identify significant predictors and their effect size (size of the coefficient).</p>
<p>We can extract the <code>model</code> object’s components with <code>$</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a>model<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept) daily_cigarettes 
      78.7147894       -0.2807398 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(model<span class="sc">$</span>residuals, <span class="at">breaks =</span> <span class="dv">30</span>, <span class="at">main =</span> <span class="st">'Histogram of residuals'</span>, </span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">'Residual'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="presentation5_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="model-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="model-interpretation">Model interpretation</h3>
<p>What do these results mean? Our model formulation is:</p>
<p><span class="math display">\[life=b_0+b_1*cigarettes\]</span></p>
<p>And we estimated these values:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>model<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept) daily_cigarettes 
      78.7147894       -0.2807398 </code></pre>
</div>
</div>
<p>Therefore:</p>
<ul>
<li><p>The intercept <span class="math inline">\(b_0\)</span> is the number of years we estimated a person in this dataset will live if they smoke 0 cigarettes. It is 78.7 years</p></li>
<li><p>The coefficient of cigarettes per day is -0.28. This means for every 1 unit increase in cigarettes (one additional cigarette per day) the life expectancy decreases by 0.28 years.</p></li>
</ul>
</section>
<section id="model-performance" class="level3">
<h3 class="anchored" data-anchor-id="model-performance">Model performance</h3>
<p>We now use our held out test data to evaluate the model performance. For that we will predict life expectancy for the 25 observations in <code>test</code> and compare with the actual values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co">#use the fitted model to make predictions for the test data</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>y_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(model, test)</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>y_pred</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       1        2        3        4        5        6        7        8 
76.74961 75.62665 71.13481 69.73112 76.46887 74.22295 77.59183 70.29260 
       9       10       11       12       13       14       15       16 
73.38073 70.01186 76.46887 75.62665 75.34591 76.46887 73.38073 75.34591 
      17       18       19       20       21       22       23       24 
76.18813 71.41555 73.66147 71.13481 71.97703 75.34591 72.25777 75.90739 
      25 
78.71479 </code></pre>
</div>
</div>
<p>Let’s see how that fits with the known values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>pred <span class="ot">&lt;-</span> <span class="fu">tibble</span>(<span class="at">pred =</span> y_pred, <span class="at">real =</span> test<span class="sc">$</span>life)</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(pred, <span class="fu">aes</span>(<span class="at">x=</span>real, <span class="at">y=</span>pred)) <span class="sc">+</span></span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="presentation5_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Not too bad! We usually calculate the mean square error (mse) between predictions and the known true values to numerically evaluate regression performance:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mse</span>(pred<span class="sc">$</span>real,pred<span class="sc">$</span>pred)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.742902</code></pre>
</div>
</div>
<p>Our predictions are on average 1.7 years wrong.</p>
</section>
</section>
<section id="regression-with-categorical-features" class="level2">
<h2 class="anchored" data-anchor-id="regression-with-categorical-features">Regression with categorical features</h2>
<p>Now that we know how to make a simple linear model, how can we include categorical variables and what is the interpretation of their coefficients? To investigate this we include the other predictor variable we have: Exercise level.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">distinct</span>(df_smoke, exercise)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 1
  exercise
     &lt;int&gt;
1        0
2        1
3        2</code></pre>
</div>
</div>
<p>Alright, we have three different levels of exercise. They are: low == 0, moderate == 1 and high == 2. Before we go on, let’s have a look if our data is represented correctly:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df_smoke)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [100 × 4] (S3: tbl_df/tbl/data.frame)
 $ daily_cigarettes: int [1:100] 7 11 27 23 13 11 20 6 23 32 ...
 $ life            : int [1:100] 76 73 72 71 74 76 71 76 72 70 ...
 $ exercise        : int [1:100] 0 0 1 0 0 1 0 1 1 2 ...
 $ ID              : int [1:100] 1 2 3 4 5 6 7 8 9 10 ...</code></pre>
</div>
</div>
<p>We can see that the <code>exercise</code> column is interpreted as an integer. However, it is actually a category! In R categorical variables are known as <code>factors</code> and have their own datatype. Let’s convert exercise to a factor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>df_smoke<span class="sc">$</span>exercise <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(df_smoke<span class="sc">$</span>exercise)</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(df_smoke)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>tibble [100 × 4] (S3: tbl_df/tbl/data.frame)
 $ daily_cigarettes: int [1:100] 7 11 27 23 13 11 20 6 23 32 ...
 $ life            : int [1:100] 76 73 72 71 74 76 71 76 72 70 ...
 $ exercise        : Factor w/ 3 levels "0","1","2": 1 1 2 1 1 2 1 2 2 3 ...
 $ ID              : int [1:100] 1 2 3 4 5 6 7 8 9 10 ...</code></pre>
</div>
</div>
<p>As before, before fitting the model we’ll split up the data in train and test. Since we’re using the same seed we should get the same observations, i.e.&nbsp;rows into training and test as above.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed to ensure reproducibility</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  </span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="co">#add an ID column to keep track of observations</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>df_smoke<span class="sc">$</span>ID <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(df_smoke)</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> df_smoke <span class="sc">%&gt;%</span> <span class="fu">sample_frac</span>(.<span class="dv">75</span>)</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a>test  <span class="ot">&lt;-</span> <span class="fu">anti_join</span>(df_smoke, train, <span class="at">by =</span> <span class="st">'ID'</span>) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And now we extend our previous model formula with the new predictor:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>model2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(life <span class="sc">~</span> daily_cigarettes <span class="sc">+</span> exercise, <span class="at">data =</span> train)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = life ~ daily_cigarettes + exercise, data = train)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.58295 -0.53972 -0.01596  0.53773  1.70257 

Coefficients:
                  Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)      77.582954   0.234237 331.216  &lt; 2e-16 ***
daily_cigarettes -0.285521   0.009401 -30.372  &lt; 2e-16 ***
exercise1         1.095475   0.249402   4.392 3.84e-05 ***
exercise2         2.372227   0.260427   9.109 1.48e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.8578 on 71 degrees of freedom
Multiple R-squared:  0.9338,    Adjusted R-squared:  0.931 
F-statistic: 333.7 on 3 and 71 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>When we check the summary we see that it has two additional coefficients, <code>exercise1</code> and <code>exercise2</code>. What are they?</p>
<p>Because <code>exercise</code> is a categorical variable it is dummy coded. That means our model formula mathematically looks something like this:</p>
<p><span class="math display">\[y=b_0+b_1*x_1 + b_2 *x_2 + b_3*x_3\]</span></p>
<p>with:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: center;">Exercise level</th>
<th style="text-align: center;"><span class="math inline">\(x_2\)</span></th>
<th style="text-align: right;"><span class="math inline">\(x_3\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">1</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">2</td>
<td style="text-align: center;">0</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
<p>And for our coefficients it means:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>model2<span class="sc">$</span>coefficients</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     (Intercept) daily_cigarettes        exercise1        exercise2 
      77.5829543       -0.2855213        1.0954747        2.3722266 </code></pre>
</div>
</div>
<ul>
<li><p><code>Intercept</code> == <span class="math inline">\(b_0\)</span>: The life expectancy at 0 cigarettes and exercise level 0</p></li>
<li><p><code>daily_cigerettes</code> == <span class="math inline">\(b_1\)</span>: The change in life expectancy for each additional cigarette.</p></li>
<li><p><code>exercise1</code> == <span class="math inline">\(b_2\)</span>: The change in life expectancy if the exercise level is 1 (assuming the number of cigarettes stays constant).</p></li>
<li><p><code>exercise2</code> == <span class="math inline">\(b_3\)</span>: The change in life expectancy if the exercise level is 2 (assuming the number of cigarettes stays constant).</p></li>
</ul>
<p>Why is there no coefficient for exercise level 0 (low amount of exercise)? This case is covered in the Intercept. It is referred to as the <strong>reference level</strong> of the categorical variable. You can change which level is regarded as the reference and the effect of having this level will always be modelled in the intercept.</p>
</section>
<section id="classification" class="level2">
<h2 class="anchored" data-anchor-id="classification">Classification</h2>
<p>Classification is what we apply when the outcome has two or more classes.</p>
<p>In order to have a categorical outcome, we’ll add a column to our toy data that describes whether the person died before age 75 or not.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>df_smoke <span class="ot">&lt;-</span> df_smoke <span class="sc">%&gt;%</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">early_death =</span> <span class="fu">factor</span>(<span class="fu">ifelse</span>(life <span class="sc">&lt;</span> <span class="dv">75</span>, <span class="st">'yes'</span>, <span class="st">'no'</span>)))</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>df_smoke <span class="sc">%&gt;%</span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(early_death)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  early_death     n
  &lt;fct&gt;       &lt;int&gt;
1 no             49
2 yes            51</code></pre>
</div>
</div>
<section id="training-and-test-set-with-class-data" class="level3">
<h3 class="anchored" data-anchor-id="training-and-test-set-with-class-data">Training and Test set with class data</h3>
<p>Let’s remake our training and test data. This time we have classes that we would like to be in the same ratios in training and test set. Therefore, we cannot just grab 75% of the data as we did before. We’ll use <code>sample.split</code> from <code>caTools</code> to achieve balanced classes:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed to ensure reproducibility</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>split <span class="ot">&lt;-</span> <span class="fu">sample.split</span>(df_smoke<span class="sc">$</span>early_death, <span class="at">SplitRatio =</span> <span class="fl">0.75</span>)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a><span class="co">#split is a vector of true and false values we can now directly apply to our tibble</span></span>
<span id="cb46-7"><a href="#cb46-7" aria-hidden="true" tabindex="-1"></a>split</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1]  TRUE FALSE  TRUE  TRUE FALSE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE
 [13]  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE FALSE
 [25]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE  TRUE
 [37] FALSE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE FALSE
 [49]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE
 [61]  TRUE FALSE  TRUE  TRUE FALSE  TRUE  TRUE FALSE  TRUE FALSE  TRUE  TRUE
 [73]  TRUE  TRUE  TRUE  TRUE FALSE  TRUE FALSE  TRUE FALSE  TRUE  TRUE  TRUE
 [85]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
 [97]  TRUE  TRUE  TRUE  TRUE</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> df_smoke[split,]</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> df_smoke[<span class="sc">!</span>split,] <span class="co">#! negates the vector, so true becomes false and vice verse</span></span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(train,early_death)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  early_death     n
  &lt;fct&gt;       &lt;int&gt;
1 no             37
2 yes            38</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="fu">count</span>(test, early_death)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  early_death     n
  &lt;fct&gt;       &lt;int&gt;
1 no             12
2 yes            13</code></pre>
</div>
</div>
<p>Now we can perform logistic regression to see whether there is an influence of the number of cigarettes and amount of exercise on the odds of the person dying before 75.</p>
<p>Logistic regression belongs to the family of generalized linear models. They all look like this:</p>
<p><span class="math display">\[ y \sim \beta * X \]</span></p>
<p>with:</p>
<ul>
<li><span class="math inline">\(y\)</span> the outcome</li>
<li><span class="math inline">\(\beta\)</span> the coefficient matrix</li>
<li><span class="math inline">\(X\)</span> the matrix of predictors</li>
<li><span class="math inline">\(\sim\)</span> the link function</li>
</ul>
<p>In a logistic regression model the link function is the logit. In a linear model the link function is the identity function (so ~ becomes =).</p>
</section>
<section id="logistic-regression-math" class="level3">
<h3 class="anchored" data-anchor-id="logistic-regression-math">Logistic regression: Math</h3>
<p>In order to understand what that means we’ll need a tiny bit of math.</p>
<p>We see some issues right of the bat. Our <span class="math inline">\(y\)</span> is either 0 or 1 (the person is either dead or not). However we cannot model that so instead we will model the probability of the outcome being 1: <span class="math inline">\(P(earlydeath == 1)\)</span>. Except probabilities are bounded between 0 and 1 which is mathematically difficult to impose (it means all <span class="math inline">\(y\)</span>’s have to be between these two values and how are we gonna enforce that?) So instead, we will model the log-odds of early death:</p>
<p><span class="math display">\[ y = \log(\frac{P(earlydeath == 1)}{1-P(earlydeath == 1)})\]</span></p>
<p>It may not look like it but we promise you this <span class="math inline">\(y\)</span> is a well behaved number because it can be anywhere between - infinity and + infinity. So therefore our actual model is:</p>
<p><span class="math display">\[ \log(\frac{P(earlydeath == 1)}{1-P(earlydeath == 1)} =  \beta * X\]</span></p>
<p>And if we want to know what the means for the probability of dying we just take the logit of <span class="math inline">\(y\)</span> :</p>
<p><span class="math display">\[ P(earlydeath == 1) = \frac{1}{1+ e^{(-y)}} \]</span></p>
<p>Which makes the link between what we’re actually interested in (people’s chances of dying) and what we’re modelling the logit. End of math.</p>
</section>
<section id="model-formulation-in-r" class="level3">
<h3 class="anchored" data-anchor-id="model-formulation-in-r">Model formulation in R</h3>
<p>So in order to fit a logistic regression we will use the function for generalized linear models, <code>glm</code>. We will specify that we want logistic regression (using the logit as the link) by setting <code>family = binomial</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>model_log <span class="ot">&lt;-</span> <span class="fu">glm</span>(early_death <span class="sc">~</span> daily_cigarettes <span class="sc">+</span> exercise, <span class="at">data =</span> train, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = early_death ~ daily_cigarettes + exercise, family = "binomial", 
    data = train)

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)      -11.0307     4.0190  -2.745  0.00606 **
daily_cigarettes   0.8380     0.2836   2.955  0.00313 **
exercise1         -1.6493     2.0986  -0.786  0.43191   
exercise2         -2.5922     2.4751  -1.047  0.29497   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 103.959  on 74  degrees of freedom
Residual deviance:  13.717  on 71  degrees of freedom
AIC: 21.717

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
</section>
<section id="model-interpretation-1" class="level3">
<h3 class="anchored" data-anchor-id="model-interpretation-1">Model interpretation</h3>
<p>We see from looking at the summary that the coefficient of exercise level 1 and level 2 is not significant. This means that we are not confident that doing a high amount of exercise (level 3) has a significant impact on the probability of dying before 75 compare to doing moderate or low amounts of exercise. This does not mean that there can be no influence, merely that we do not have enough data to detect it if it is there.</p>
<p>Are you surprised? Exercise level was significant when we modelled the number of years lived, which is arguably a more fine-grained information than the binary split and perhaps therefore we picked up the influence.</p>
<p>With the number of daily cigarettes predictor we have a high degree of certainty that it influences the probability of dying before 75 (in this dataset!), but what does a coefficient of 0.84 mean?</p>
<p>We know that:</p>
<p><span class="math display">\[ P(earlydeath == 1) = \frac{1}{1+ e^{(-y)}} \]</span></p>
<p>and (leaving out the exercise level since it’s not significant):</p>
<p><span class="math display">\[ y = \beta_0 + \beta_1 * cigs \]</span></p>
<p>So how does <span class="math inline">\(y\)</span> change as <span class="math inline">\(0.84 * cigs\)</span> becomes larger? Let’s agree that <span class="math inline">\(y\)</span> becomes larger. What does that mean for the probability of dying? Is <span class="math inline">\(e^{(-y)}\)</span> a large number if <span class="math inline">\(y\)</span> is large? Luckily we have a calculator handy</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co">#exp(b) is e^b in R</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3678794</code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="dv">10</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 4.539993e-05</code></pre>
</div>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">exp</span>(<span class="sc">-</span><span class="dv">100</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.720076e-44</code></pre>
</div>
</div>
<p>We see that <span class="math inline">\(e^{(-y)}\)</span> becomes increasingly smaller with larger <span class="math inline">\(y\)</span> which means that</p>
<p><span class="math display">\[ P(earlydeath == 1) = \frac{1}{1+ small} \sim \frac{1}{1} \]</span></p>
<p>So the larger <span class="math inline">\(y\)</span> the smaller <span class="math inline">\(e^{(-y)}\)</span> and the closer we get to <span class="math inline">\(P(earlydeath == 1)\)</span> being 1. That was a lot of math for: If the coefficient is positive you increase the likelihood of getting the outcome, i.e.&nbsp;dying.</p>
</section>
<section id="model-comparison" class="level3">
<h3 class="anchored" data-anchor-id="model-comparison">Model comparison</h3>
<p>So now we know how to fit linear models and interpret the results. But often there are several predictors we could include or not include, so how do we know that one model is better than another?</p>
<p>There are several ways to compare models. One is the likelihood ratio test which tests whether adding predictors significantly improves model fit by comparing the log-likelihoods of the two models. Another much used comparison is to look at the AIC (Akaike Information Criterion) or BIC (Bayesian Information Criterion). Lower AIC/BIC values generally indicate a better trade-off between model fit and complexity.</p>
<p>For example we have made this model above:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_log)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = early_death ~ daily_cigarettes + exercise, family = "binomial", 
    data = train)

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)      -11.0307     4.0190  -2.745  0.00606 **
daily_cigarettes   0.8380     0.2836   2.955  0.00313 **
exercise1         -1.6493     2.0986  -0.786  0.43191   
exercise2         -2.5922     2.4751  -1.047  0.29497   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 103.959  on 74  degrees of freedom
Residual deviance:  13.717  on 71  degrees of freedom
AIC: 21.717

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p>But <code>exercise</code> does not have a significant p-value. Perhaps we would have a better model if we only use <code>dialy_cigarettes</code>?</p>
<p>Let’s compare them:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a>model_reduced <span class="ot">&lt;-</span> <span class="fu">glm</span>(early_death <span class="sc">~</span> daily_cigarettes, <span class="at">data =</span> train, <span class="at">family =</span> <span class="st">"binomial"</span>)</span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(model_reduced)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
glm(formula = early_death ~ daily_cigarettes, family = "binomial", 
    data = train)

Coefficients:
                 Estimate Std. Error z value Pr(&gt;|z|)   
(Intercept)      -11.7674     3.7944  -3.101  0.00193 **
daily_cigarettes   0.7753     0.2547   3.044  0.00233 **
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

(Dispersion parameter for binomial family taken to be 1)

    Null deviance: 103.959  on 74  degrees of freedom
Residual deviance:  15.006  on 73  degrees of freedom
AIC: 19.006

Number of Fisher Scoring iterations: 8</code></pre>
</div>
</div>
<p>We can use an anova with the Chi-square test to compare the log-likelihood of the two models:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(model_log, model_reduced, <span class="at">test =</span> <span class="st">'Chisq'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Deviance Table

Model 1: early_death ~ daily_cigarettes + exercise
Model 2: early_death ~ daily_cigarettes
  Resid. Df Resid. Dev Df Deviance Pr(&gt;Chi)
1        71     13.717                     
2        73     15.006 -2  -1.2891   0.5249</code></pre>
</div>
</div>
<p>The p-value of the Chi-square test tells us if there is evidence that the difference in log-likelihoods is significant. If it is not significant, we do not have evidence that one model is a better fit than the other and we would therefore choose the less complex model with fewer predictors since that gives us more statistical power and less overfitting.</p>
</section>
</section>
<section id="clustering" class="level2">
<h2 class="anchored" data-anchor-id="clustering">Clustering</h2>
<p>Clustering is a type of unsupervised learning technique used to group similar data points together based on their features. The goal is to find inherent patterns or structures within the data, e.g.&nbsp;to see whether the data points fall into distinct groups with distinct features or not.</p>
<section id="wine-dataset" class="level3">
<h3 class="anchored" data-anchor-id="wine-dataset">Wine dataset</h3>
<p>For this we will use the wine data set as an example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb66"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ContaminatedMixt)</span>
<span id="cb66-2"><a href="#cb66-2" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(<span class="st">'wine'</span>) <span class="co">#load dataset</span></span>
<span id="cb66-3"><a href="#cb66-3" aria-hidden="true" tabindex="-1"></a>df_wine <span class="ot">&lt;-</span> wine <span class="co">#convert to tibble</span></span>
<span id="cb66-4"><a href="#cb66-4" aria-hidden="true" tabindex="-1"></a>df_wine</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          Type Alcohol Malic  Ash Alcalinity Magnesium Phenols Flavanoids
1       Barolo   14.23  1.71 2.43       15.6       127    2.80       3.06
2       Barolo   13.20  1.78 2.14       11.2       100    2.65       2.76
3       Barolo   13.16  2.36 2.67       18.6       101    2.80       3.24
4       Barolo   14.37  1.95 2.50       16.8       113    3.85       3.49
5       Barolo   13.24  2.59 2.87       21.0       118    2.80       2.69
6       Barolo   14.20  1.76 2.45       15.2       112    3.27       3.39
7       Barolo   14.39  1.87 2.45       14.6        96    2.50       2.52
8       Barolo   14.06  2.15 2.61       17.6       121    2.60       2.51
9       Barolo   14.83  1.64 2.17       14.0        97    2.80       2.98
10      Barolo   13.86  1.35 2.27       16.0        98    2.98       3.15
11      Barolo   14.10  2.16 2.30       18.0       105    2.95       3.32
12      Barolo   14.12  1.48 2.32       16.8        95    2.20       2.43
13      Barolo   13.75  1.73 2.41       16.0        89    2.60       2.76
14      Barolo   14.75  1.73 2.39       11.4        91    3.10       3.69
15      Barolo   14.38  1.87 2.38       12.0       102    3.30       3.64
16      Barolo   13.63  1.81 2.70       17.2       112    2.85       2.91
17      Barolo   14.30  1.92 2.72       20.0       120    2.80       3.14
18      Barolo   13.83  1.57 2.62       20.0       115    2.95       3.40
19      Barolo   14.19  1.59 2.48       16.5       108    3.30       3.93
20      Barolo   13.64  3.10 2.56       15.2       116    2.70       3.03
21      Barolo   14.06  1.63 2.28       16.0       126    3.00       3.17
22      Barolo   12.93  3.80 2.65       18.6       102    2.41       2.41
23      Barolo   13.71  1.86 2.36       16.6       101    2.61       2.88
24      Barolo   12.85  1.60 2.52       17.8        95    2.48       2.37
25      Barolo   13.50  1.81 2.61       20.0        96    2.53       2.61
26      Barolo   13.05  2.05 3.22       25.0       124    2.63       2.68
27      Barolo   13.39  1.77 2.62       16.1        93    2.85       2.94
28      Barolo   13.30  1.72 2.14       17.0        94    2.40       2.19
29      Barolo   13.87  1.90 2.80       19.4       107    2.95       2.97
30      Barolo   14.02  1.68 2.21       16.0        96    2.65       2.33
31      Barolo   13.73  1.50 2.70       22.5       101    3.00       3.25
32      Barolo   13.58  1.66 2.36       19.1       106    2.86       3.19
33      Barolo   13.68  1.83 2.36       17.2       104    2.42       2.69
34      Barolo   13.76  1.53 2.70       19.5       132    2.95       2.74
35      Barolo   13.51  1.80 2.65       19.0       110    2.35       2.53
36      Barolo   13.48  1.81 2.41       20.5       100    2.70       2.98
37      Barolo   13.28  1.64 2.84       15.5       110    2.60       2.68
38      Barolo   13.05  1.65 2.55       18.0        98    2.45       2.43
39      Barolo   13.07  1.50 2.10       15.5        98    2.40       2.64
40      Barolo   14.22  3.99 2.51       13.2       128    3.00       3.04
41      Barolo   13.56  1.71 2.31       16.2       117    3.15       3.29
42      Barolo   13.41  3.84 2.12       18.8        90    2.45       2.68
43      Barolo   13.88  1.89 2.59       15.0       101    3.25       3.56
44      Barolo   13.24  3.98 2.29       17.5       103    2.64       2.63
45      Barolo   13.05  1.77 2.10       17.0       107    3.00       3.00
46      Barolo   14.21  4.04 2.44       18.9       111    2.85       2.65
47      Barolo   14.38  3.59 2.28       16.0       102    3.25       3.17
48      Barolo   13.90  1.68 2.12       16.0       101    3.10       3.39
49      Barolo   14.10  2.02 2.40       18.8       103    2.75       2.92
50      Barolo   13.94  1.73 2.27       17.4       108    2.88       3.54
51      Barolo   13.05  1.73 2.04       12.4        92    2.72       3.27
52      Barolo   13.83  1.65 2.60       17.2        94    2.45       2.99
53      Barolo   13.82  1.75 2.42       14.0       111    3.88       3.74
54      Barolo   13.77  1.90 2.68       17.1       115    3.00       2.79
55      Barolo   13.74  1.67 2.25       16.4       118    2.60       2.90
56      Barolo   13.56  1.73 2.46       20.5       116    2.96       2.78
57      Barolo   14.22  1.70 2.30       16.3       118    3.20       3.00
58      Barolo   13.29  1.97 2.68       16.8       102    3.00       3.23
59      Barolo   13.72  1.43 2.50       16.7       108    3.40       3.67
60  Grignolino   12.37  0.94 1.36       10.6        88    1.98       0.57
61  Grignolino   12.33  1.10 2.28       16.0       101    2.05       1.09
62  Grignolino   12.64  1.36 2.02       16.8       100    2.02       1.41
63  Grignolino   13.67  1.25 1.92       18.0        94    2.10       1.79
64  Grignolino   12.37  1.13 2.16       19.0        87    3.50       3.10
65  Grignolino   12.17  1.45 2.53       19.0       104    1.89       1.75
66  Grignolino   12.37  1.21 2.56       18.1        98    2.42       2.65
67  Grignolino   13.11  1.01 1.70       15.0        78    2.98       3.18
68  Grignolino   12.37  1.17 1.92       19.6        78    2.11       2.00
69  Grignolino   13.34  0.94 2.36       17.0       110    2.53       1.30
70  Grignolino   12.21  1.19 1.75       16.8       151    1.85       1.28
71  Grignolino   12.29  1.61 2.21       20.4       103    1.10       1.02
72  Grignolino   13.86  1.51 2.67       25.0        86    2.95       2.86
73  Grignolino   13.49  1.66 2.24       24.0        87    1.88       1.84
74  Grignolino   12.99  1.67 2.60       30.0       139    3.30       2.89
75  Grignolino   11.96  1.09 2.30       21.0       101    3.38       2.14
76  Grignolino   11.66  1.88 1.92       16.0        97    1.61       1.57
77  Grignolino   13.03  0.90 1.71       16.0        86    1.95       2.03
78  Grignolino   11.84  2.89 2.23       18.0       112    1.72       1.32
79  Grignolino   12.33  0.99 1.95       14.8       136    1.90       1.85
80  Grignolino   12.70  3.87 2.40       23.0       101    2.83       2.55
81  Grignolino   12.00  0.92 2.00       19.0        86    2.42       2.26
82  Grignolino   12.72  1.81 2.20       18.8        86    2.20       2.53
83  Grignolino   12.08  1.13 2.51       24.0        78    2.00       1.58
84  Grignolino   13.05  3.86 2.32       22.5        85    1.65       1.59
85  Grignolino   11.84  0.89 2.58       18.0        94    2.20       2.21
86  Grignolino   12.67  0.98 2.24       18.0        99    2.20       1.94
87  Grignolino   12.16  1.61 2.31       22.8        90    1.78       1.69
88  Grignolino   11.65  1.67 2.62       26.0        88    1.92       1.61
89  Grignolino   11.64  2.06 2.46       21.6        84    1.95       1.69
90  Grignolino   12.08  1.33 2.30       23.6        70    2.20       1.59
91  Grignolino   12.08  1.83 2.32       18.5        81    1.60       1.50
92  Grignolino   12.00  1.51 2.42       22.0        86    1.45       1.25
93  Grignolino   12.69  1.53 2.26       20.7        80    1.38       1.46
94  Grignolino   12.29  2.83 2.22       18.0        88    2.45       2.25
95  Grignolino   11.62  1.99 2.28       18.0        98    3.02       2.26
96  Grignolino   12.47  1.52 2.20       19.0       162    2.50       2.27
97  Grignolino   11.81  2.12 2.74       21.5       134    1.60       0.99
98  Grignolino   12.29  1.41 1.98       16.0        85    2.55       2.50
99  Grignolino   12.37  1.07 2.10       18.5        88    3.52       3.75
100 Grignolino   12.29  3.17 2.21       18.0        88    2.85       2.99
101 Grignolino   12.08  2.08 1.70       17.5        97    2.23       2.17
102 Grignolino   12.60  1.34 1.90       18.5        88    1.45       1.36
103 Grignolino   12.34  2.45 2.46       21.0        98    2.56       2.11
104 Grignolino   11.82  1.72 1.88       19.5        86    2.50       1.64
105 Grignolino   12.51  1.73 1.98       20.5        85    2.20       1.92
106 Grignolino   12.42  2.55 2.27       22.0        90    1.68       1.84
107 Grignolino   12.25  1.73 2.12       19.0        80    1.65       2.03
108 Grignolino   12.72  1.75 2.28       22.5        84    1.38       1.76
109 Grignolino   12.22  1.29 1.94       19.0        92    2.36       2.04
110 Grignolino   11.61  1.35 2.70       20.0        94    2.74       2.92
111 Grignolino   11.46  3.74 1.82       19.5       107    3.18       2.58
112 Grignolino   12.52  2.43 2.17       21.0        88    2.55       2.27
113 Grignolino   11.76  2.68 2.92       20.0       103    1.75       2.03
114 Grignolino   11.41  0.74 2.50       21.0        88    2.48       2.01
115 Grignolino   12.08  1.39 2.50       22.5        84    2.56       2.29
116 Grignolino   11.03  1.51 2.20       21.5        85    2.46       2.17
117 Grignolino   11.82  1.47 1.99       20.8        86    1.98       1.60
118 Grignolino   12.42  1.61 2.19       22.5       108    2.00       2.09
119 Grignolino   12.77  3.43 1.98       16.0        80    1.63       1.25
120 Grignolino   12.00  3.43 2.00       19.0        87    2.00       1.64
121 Grignolino   11.45  2.40 2.42       20.0        96    2.90       2.79
122 Grignolino   11.56  2.05 3.23       28.5       119    3.18       5.08
123 Grignolino   12.42  4.43 2.73       26.5       102    2.20       2.13
124 Grignolino   13.05  5.80 2.13       21.5        86    2.62       2.65
125 Grignolino   11.87  4.31 2.39       21.0        82    2.86       3.03
126 Grignolino   12.07  2.16 2.17       21.0        85    2.60       2.65
127 Grignolino   12.43  1.53 2.29       21.5        86    2.74       3.15
128 Grignolino   11.79  2.13 2.78       28.5        92    2.13       2.24
129 Grignolino   12.37  1.63 2.30       24.5        88    2.22       2.45
130 Grignolino   12.04  4.30 2.38       22.0        80    2.10       1.75
131    Barbera   12.86  1.35 2.32       18.0       122    1.51       1.25
132    Barbera   12.88  2.99 2.40       20.0       104    1.30       1.22
133    Barbera   12.81  2.31 2.40       24.0        98    1.15       1.09
134    Barbera   12.70  3.55 2.36       21.5       106    1.70       1.20
135    Barbera   12.51  1.24 2.25       17.5        85    2.00       0.58
136    Barbera   12.60  2.46 2.20       18.5        94    1.62       0.66
137    Barbera   12.25  4.72 2.54       21.0        89    1.38       0.47
138    Barbera   12.53  5.51 2.64       25.0        96    1.79       0.60
139    Barbera   13.49  3.59 2.19       19.5        88    1.62       0.48
140    Barbera   12.84  2.96 2.61       24.0       101    2.32       0.60
141    Barbera   12.93  2.81 2.70       21.0        96    1.54       0.50
142    Barbera   13.36  2.56 2.35       20.0        89    1.40       0.50
143    Barbera   13.52  3.17 2.72       23.5        97    1.55       0.52
144    Barbera   13.62  4.95 2.35       20.0        92    2.00       0.80
145    Barbera   12.25  3.88 2.20       18.5       112    1.38       0.78
146    Barbera   13.16  3.57 2.15       21.0       102    1.50       0.55
147    Barbera   13.88  5.04 2.23       20.0        80    0.98       0.34
148    Barbera   12.87  4.61 2.48       21.5        86    1.70       0.65
149    Barbera   13.32  3.24 2.38       21.5        92    1.93       0.76
150    Barbera   13.08  3.90 2.36       21.5       113    1.41       1.39
151    Barbera   13.50  3.12 2.62       24.0       123    1.40       1.57
152    Barbera   12.79  2.67 2.48       22.0       112    1.48       1.36
153    Barbera   13.11  1.90 2.75       25.5       116    2.20       1.28
154    Barbera   13.23  3.30 2.28       18.5        98    1.80       0.83
155    Barbera   12.58  1.29 2.10       20.0       103    1.48       0.58
156    Barbera   13.17  5.19 2.32       22.0        93    1.74       0.63
157    Barbera   13.84  4.12 2.38       19.5        89    1.80       0.83
158    Barbera   12.45  3.03 2.64       27.0        97    1.90       0.58
159    Barbera   14.34  1.68 2.70       25.0        98    2.80       1.31
160    Barbera   13.48  1.67 2.64       22.5        89    2.60       1.10
161    Barbera   12.36  3.83 2.38       21.0        88    2.30       0.92
162    Barbera   13.69  3.26 2.54       20.0       107    1.83       0.56
163    Barbera   12.85  3.27 2.58       22.0       106    1.65       0.60
164    Barbera   12.96  3.45 2.35       18.5       106    1.39       0.70
165    Barbera   13.78  2.76 2.30       22.0        90    1.35       0.68
166    Barbera   13.73  4.36 2.26       22.5        88    1.28       0.47
167    Barbera   13.45  3.70 2.60       23.0       111    1.70       0.92
168    Barbera   12.82  3.37 2.30       19.5        88    1.48       0.66
169    Barbera   13.58  2.58 2.69       24.5       105    1.55       0.84
170    Barbera   13.40  4.60 2.86       25.0       112    1.98       0.96
171    Barbera   12.20  3.03 2.32       19.0        96    1.25       0.49
172    Barbera   12.77  2.39 2.28       19.5        86    1.39       0.51
173    Barbera   14.16  2.51 2.48       20.0        91    1.68       0.70
174    Barbera   13.71  5.65 2.45       20.5        95    1.68       0.61
175    Barbera   13.40  3.91 2.48       23.0       102    1.80       0.75
176    Barbera   13.27  4.28 2.26       20.0       120    1.59       0.69
177    Barbera   13.17  2.59 2.37       20.0       120    1.65       0.68
178    Barbera   14.13  4.10 2.74       24.5        96    2.05       0.76
    Nonflavanoid Proanthocyanins     Color   Hue Dilution Proline
1           0.28            2.29  5.640000 1.040     3.92    1065
2           0.26            1.28  4.380000 1.050     3.40    1050
3           0.30            2.81  5.680000 1.030     3.17    1185
4           0.24            2.18  7.800000 0.860     3.45    1480
5           0.39            1.82  4.320000 1.040     2.93     735
6           0.34            1.97  6.750000 1.050     2.85    1450
7           0.30            1.98  5.250000 1.020     3.58    1290
8           0.31            1.25  5.050000 1.060     3.58    1295
9           0.29            1.98  5.200000 1.080     2.85    1045
10          0.22            1.85  7.220000 1.010     3.55    1045
11          0.22            2.38  5.750000 1.250     3.17    1510
12          0.26            1.57  5.000000 1.170     2.82    1280
13          0.29            1.81  5.600000 1.150     2.90    1320
14          0.43            2.81  5.400000 1.250     2.73    1150
15          0.29            2.96  7.500000 1.200     3.00    1547
16          0.30            1.46  7.300000 1.280     2.88    1310
17          0.33            1.97  6.200000 1.070     2.65    1280
18          0.40            1.72  6.600000 1.130     2.57    1130
19          0.32            1.86  8.700000 1.230     2.82    1680
20          0.17            1.66  5.100000 0.960     3.36     845
21          0.24            2.10  5.650000 1.090     3.71     780
22          0.25            1.98  4.500000 1.030     3.52     770
23          0.27            1.69  3.800000 1.110     4.00    1035
24          0.26            1.46  3.930000 1.090     3.63    1015
25          0.28            1.66  3.520000 1.120     3.82     845
26          0.47            1.92  3.580000 1.130     3.20     830
27          0.34            1.45  4.800000 0.920     3.22    1195
28          0.27            1.35  3.950000 1.020     2.77    1285
29          0.37            1.76  4.500000 1.250     3.40     915
30          0.26            1.98  4.700000 1.040     3.59    1035
31          0.29            2.38  5.700000 1.190     2.71    1285
32          0.22            1.95  6.900000 1.090     2.88    1515
33          0.42            1.97  3.840000 1.230     2.87     990
34          0.50            1.35  5.400000 1.250     3.00    1235
35          0.29            1.54  4.200000 1.100     2.87    1095
36          0.26            1.86  5.100000 1.040     3.47     920
37          0.34            1.36  4.600000 1.090     2.78     880
38          0.29            1.44  4.250000 1.120     2.51    1105
39          0.28            1.37  3.700000 1.180     2.69    1020
40          0.20            2.08  5.100000 0.890     3.53     760
41          0.34            2.34  6.130000 0.950     3.38     795
42          0.27            1.48  4.280000 0.910     3.00    1035
43          0.17            1.70  5.430000 0.880     3.56    1095
44          0.32            1.66  4.360000 0.820     3.00     680
45          0.28            2.03  5.040000 0.880     3.35     885
46          0.30            1.25  5.240000 0.870     3.33    1080
47          0.27            2.19  4.900000 1.040     3.44    1065
48          0.21            2.14  6.100000 0.910     3.33     985
49          0.32            2.38  6.200000 1.070     2.75    1060
50          0.32            2.08  8.900000 1.120     3.10    1260
51          0.17            2.91  7.200000 1.120     2.91    1150
52          0.22            2.29  5.600000 1.240     3.37    1265
53          0.32            1.87  7.050000 1.010     3.26    1190
54          0.39            1.68  6.300000 1.130     2.93    1375
55          0.21            1.62  5.850000 0.920     3.20    1060
56          0.20            2.45  6.250000 0.980     3.03    1120
57          0.26            2.03  6.380000 0.940     3.31     970
58          0.31            1.66  6.000000 1.070     2.84    1270
59          0.19            2.04  6.800000 0.890     2.87    1285
60          0.28            0.42  1.950000 1.050     1.82     520
61          0.63            0.41  3.270000 1.250     1.67     680
62          0.53            0.62  5.750000 0.980     1.59     450
63          0.32            0.73  3.800000 1.230     2.46     630
64          0.19            1.87  4.450000 1.220     2.87     420
65          0.45            1.03  2.950000 1.450     2.23     355
66          0.37            2.08  4.600000 1.190     2.30     678
67          0.26            2.28  5.300000 1.120     3.18     502
68          0.27            1.04  4.680000 1.120     3.48     510
69          0.55            0.42  3.170000 1.020     1.93     750
70          0.14            2.50  2.850000 1.280     3.07     718
71          0.37            1.46  3.050000 0.906     1.82     870
72          0.21            1.87  3.380000 1.360     3.16     410
73          0.27            1.03  3.740000 0.980     2.78     472
74          0.21            1.96  3.350000 1.310     3.50     985
75          0.13            1.65  3.210000 0.990     3.13     886
76          0.34            1.15  3.800000 1.230     2.14     428
77          0.24            1.46  4.600000 1.190     2.48     392
78          0.43            0.95  2.650000 0.960     2.52     500
79          0.35            2.76  3.400000 1.060     2.31     750
80          0.43            1.95  2.570000 1.190     3.13     463
81          0.30            1.43  2.500000 1.380     3.12     278
82          0.26            1.77  3.900000 1.160     3.14     714
83          0.40            1.40  2.200000 1.310     2.72     630
84          0.61            1.62  4.800000 0.840     2.01     515
85          0.22            2.35  3.050000 0.790     3.08     520
86          0.30            1.46  2.620000 1.230     3.16     450
87          0.43            1.56  2.450000 1.330     2.26     495
88          0.40            1.34  2.600000 1.360     3.21     562
89          0.48            1.35  2.800000 1.000     2.75     680
90          0.42            1.38  1.740000 1.070     3.21     625
91          0.52            1.64  2.400000 1.080     2.27     480
92          0.50            1.63  3.600000 1.050     2.65     450
93          0.58            1.62  3.050000 0.960     2.06     495
94          0.25            1.99  2.150000 1.150     3.30     290
95          0.17            1.35  3.250000 1.160     2.96     345
96          0.32            3.28  2.600000 1.160     2.63     937
97          0.14            1.56  2.500000 0.950     2.26     625
98          0.29            1.77  2.900000 1.230     2.74     428
99          0.24            1.95  4.500000 1.040     2.77     660
100         0.45            2.81  2.300000 1.420     2.83     406
101         0.26            1.40  3.300000 1.270     2.96     710
102         0.29            1.35  2.450000 1.040     2.77     562
103         0.34            1.31  2.800000 0.800     3.38     438
104         0.37            1.42  2.060000 0.940     2.44     415
105         0.32            1.48  2.940000 1.040     3.57     672
106         0.66            1.42  2.700000 0.860     3.30     315
107         0.37            1.63  3.400000 1.000     3.17     510
108         0.48            1.63  3.300000 0.880     2.42     488
109         0.39            2.08  2.700000 0.860     3.02     312
110         0.29            2.49  2.650000 0.960     3.26     680
111         0.24            3.58  2.900000 0.750     2.81     562
112         0.26            1.22  2.000000 0.900     2.78     325
113         0.60            1.05  3.800000 1.230     2.50     607
114         0.42            1.44  3.080000 1.100     2.31     434
115         0.43            1.04  2.900000 0.930     3.19     385
116         0.52            2.01  1.900000 1.710     2.87     407
117         0.30            1.53  1.950000 0.950     3.33     495
118         0.34            1.61  2.060000 1.060     2.96     345
119         0.43            0.83  3.400000 0.700     2.12     372
120         0.37            1.87  1.280000 0.930     3.05     564
121         0.32            1.83  3.250000 0.800     3.39     625
122         0.47            1.87  6.000000 0.930     3.69     465
123         0.43            1.71  2.080000 0.920     3.12     365
124         0.30            2.01  2.600000 0.730     3.10     380
125         0.21            2.91  2.800000 0.750     3.64     380
126         0.37            1.35  2.760000 0.860     3.28     378
127         0.39            1.77  3.940000 0.690     2.84     352
128         0.58            1.76  3.000000 0.970     2.44     466
129         0.40            1.90  2.120000 0.890     2.78     342
130         0.42            1.35  2.600000 0.790     2.57     580
131         0.21            0.94  4.100000 0.760     1.29     630
132         0.24            0.83  5.400000 0.740     1.42     530
133         0.27            0.83  5.700000 0.660     1.36     560
134         0.17            0.84  5.000000 0.780     1.29     600
135         0.60            1.25  5.450000 0.750     1.51     650
136         0.63            0.94  7.100000 0.730     1.58     695
137         0.53            0.80  3.850000 0.750     1.27     720
138         0.63            1.10  5.000000 0.820     1.69     515
139         0.58            0.88  5.700000 0.810     1.82     580
140         0.53            0.81  4.920000 0.890     2.15     590
141         0.53            0.75  4.600000 0.770     2.31     600
142         0.37            0.64  5.600000 0.700     2.47     780
143         0.50            0.55  4.350000 0.890     2.06     520
144         0.47            1.02  4.400000 0.910     2.05     550
145         0.29            1.14  8.210000 0.650     2.00     855
146         0.43            1.30  4.000000 0.600     1.68     830
147         0.40            0.68  4.900000 0.580     1.33     415
148         0.47            0.86  7.650000 0.540     1.86     625
149         0.45            1.25  8.420000 0.550     1.62     650
150         0.34            1.14  9.400000 0.570     1.33     550
151         0.22            1.25  8.600000 0.590     1.30     500
152         0.24            1.26 10.800000 0.480     1.47     480
153         0.26            1.56  7.100000 0.610     1.33     425
154         0.61            1.87 10.520000 0.560     1.51     675
155         0.53            1.40  7.600000 0.580     1.55     640
156         0.61            1.55  7.900000 0.600     1.48     725
157         0.48            1.56  9.010000 0.570     1.64     480
158         0.63            1.14  7.500000 0.670     1.73     880
159         0.53            2.70 13.000000 0.570     1.96     660
160         0.52            2.29 11.750000 0.570     1.78     620
161         0.50            1.04  7.650000 0.560     1.58     520
162         0.50            0.80  5.880000 0.960     1.82     680
163         0.60            0.96  5.580000 0.870     2.11     570
164         0.40            0.94  5.280000 0.680     1.75     675
165         0.41            1.03  9.580000 0.700     1.68     615
166         0.52            1.15  6.620000 0.780     1.75     520
167         0.43            1.46 10.680000 0.850     1.56     695
168         0.40            0.97 10.260000 0.720     1.75     685
169         0.39            1.54  8.660000 0.740     1.80     750
170         0.27            1.11  8.500000 0.670     1.92     630
171         0.40            0.73  5.500000 0.660     1.83     510
172         0.48            0.64  9.899999 0.570     1.63     470
173         0.44            1.24  9.700000 0.620     1.71     660
174         0.52            1.06  7.700000 0.640     1.74     740
175         0.43            1.41  7.300000 0.700     1.56     750
176         0.43            1.35 10.200000 0.590     1.56     835
177         0.53            1.46  9.300000 0.600     1.62     840
178         0.56            1.35  9.200000 0.610     1.60     560</code></pre>
</div>
</div>
<p>This dataset contains 178 wine, each corresponding to one of three different cultivars of wine. It has 13 numerical columns that record different features of the wine.</p>
<p>We will try out a popular method, k-means clustering. It works by initializing K centroids and assigning each data point to the nearest centroid. The algorithm then recalculates the centroids as the mean of the points in each cluster, repeating the process until the clusters stabilize. You can see an illustration of the process below. Its weakness is that we need to define the number of centroids, i.e.&nbsp;clusters, beforehand.</p>
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="../figures/kmeans.jpg" class="img-fluid quarto-figure quarto-figure-center figure-img"></p>
</figure>
</div>
</section>
<section id="running-k-means" class="level3">
<h3 class="anchored" data-anchor-id="running-k-means">Running k-means</h3>
<p>For k-means it is very important that the data is numeric and scaled so we will do that before running the algorithm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb68"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed to ensure reproducibility</span></span>
<span id="cb68-2"><a href="#cb68-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  </span>
<span id="cb68-3"><a href="#cb68-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-4"><a href="#cb68-4" aria-hidden="true" tabindex="-1"></a><span class="co">#run kmeans</span></span>
<span id="cb68-5"><a href="#cb68-5" aria-hidden="true" tabindex="-1"></a>kmeans_res <span class="ot">&lt;-</span> df_wine <span class="sc">%&gt;%</span></span>
<span id="cb68-6"><a href="#cb68-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb68-7"><a href="#cb68-7" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale all numeric cols</span></span>
<span id="cb68-8"><a href="#cb68-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), scale)) <span class="sc">%&gt;%</span></span>
<span id="cb68-9"><a href="#cb68-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kmeans</span>(<span class="at">centers =</span> <span class="dv">4</span>, <span class="at">nstart =</span> <span class="dv">25</span>)</span>
<span id="cb68-10"><a href="#cb68-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb68-11"><a href="#cb68-11" aria-hidden="true" tabindex="-1"></a>kmeans_res</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>K-means clustering with 4 clusters of sizes 28, 56, 49, 45

Cluster means:
     Alcohol       Malic        Ash Alcalinity   Magnesium    Phenols
1 -0.7869073  0.04195151  0.2157781  0.3683284  0.43818899  0.6543578
2  0.9580555 -0.37748461  0.1969019 -0.8214121  0.39943022  0.9000233
3  0.1860184  0.90242582  0.2485092  0.5820616 -0.05049296 -0.9857762
4 -0.9051690 -0.53898599 -0.6498944  0.1592193 -0.71473842 -0.4537841
  Flavanoids Nonflavanoid Proanthocyanins      Color        Hue    Dilution
1  0.5746004   -0.5429201       0.8888549 -0.7346332  0.2830335  0.60628629
2  0.9848901   -0.6204018       0.5575193  0.2423047  0.4799084  0.76926636
3 -1.2327174    0.7148253      -0.7474990  0.9857177 -1.1879477 -1.29787850
4 -0.2408779    0.3315072      -0.4329238 -0.9177666  0.5202140  0.07869143
     Proline
1 -0.5169332
2  1.2184972
3 -0.3789756
4 -0.7820425

Clustering vector:
  [1] 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2
 [38] 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 4 4 4 4 1 4 1 2 4 4 1 4 1 4 1
 [75] 1 4 4 4 1 1 4 4 4 3 1 4 4 4 4 4 4 4 4 1 1 1 1 4 1 1 4 4 1 4 4 4 4 4 4 1 1
[112] 4 4 4 4 4 4 4 4 4 1 1 1 1 1 4 1 4 4 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
[149] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3

Within cluster sum of squares by cluster:
[1] 307.0966 268.5747 302.9915 289.9515
 (between_SS / total_SS =  49.2 %)

Available components:

[1] "cluster"      "centers"      "totss"        "withinss"     "tot.withinss"
[6] "betweenss"    "size"         "iter"         "ifault"      </code></pre>
</div>
</div>
<p>We get a lot of results. <code>kmeans_res$cluster</code> is the cluster assigned to every wine bottle, i.e.&nbsp;row:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb70"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1" aria-hidden="true" tabindex="-1"></a>kmeans_res<span class="sc">$</span>cluster</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  [1] 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2
 [38] 2 2 2 2 2 2 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 4 4 4 4 1 4 1 2 4 4 1 4 1 4 1
 [75] 1 4 4 4 1 1 4 4 4 3 1 4 4 4 4 4 4 4 4 1 1 1 1 4 1 1 4 4 1 4 4 4 4 4 4 1 1
[112] 4 4 4 4 4 4 4 4 4 1 1 1 1 1 4 1 4 4 4 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3
[149] 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3 3</code></pre>
</div>
</div>
<p>And <code>kmeans_res$centers</code> shows us at which values the centroids are:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb72"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb72-1"><a href="#cb72-1" aria-hidden="true" tabindex="-1"></a>kmeans_res<span class="sc">$</span>centers</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Alcohol       Malic        Ash Alcalinity   Magnesium    Phenols
1 -0.7869073  0.04195151  0.2157781  0.3683284  0.43818899  0.6543578
2  0.9580555 -0.37748461  0.1969019 -0.8214121  0.39943022  0.9000233
3  0.1860184  0.90242582  0.2485092  0.5820616 -0.05049296 -0.9857762
4 -0.9051690 -0.53898599 -0.6498944  0.1592193 -0.71473842 -0.4537841
  Flavanoids Nonflavanoid Proanthocyanins      Color        Hue    Dilution
1  0.5746004   -0.5429201       0.8888549 -0.7346332  0.2830335  0.60628629
2  0.9848901   -0.6204018       0.5575193  0.2423047  0.4799084  0.76926636
3 -1.2327174    0.7148253      -0.7474990  0.9857177 -1.1879477 -1.29787850
4 -0.2408779    0.3315072      -0.4329238 -0.9177666  0.5202140  0.07869143
     Proline
1 -0.5169332
2  1.2184972
3 -0.3789756
4 -0.7820425</code></pre>
</div>
</div>
<p>For example the center of cluster 1 is placed at the coordinates -0.79 for Alcohol, 0.04 for Malic Acid, 0.22 for Ash and so on. Since our data has 13 dimensions, i.e.&nbsp;features, the cluster centers also do.</p>
<p>This is not super practical if we would like to visually inspect the clustering since we cannot plot in 13 dimensions. How could we solve this?</p>
</section>
<section id="visualizing-k-means-results" class="level3">
<h3 class="anchored" data-anchor-id="visualizing-k-means-results">Visualizing k-means results</h3>
<p>We would like to see where our wine bottles and their clusters lie in a low-dimensional space so we will calculate a PCA of the wine data and map the cluster centers to the PCA space.</p>
<p>Since we want the PCA space and the clustering to have the same mapping we’ll scale the data before running <code>prcomp()</code>. Basically we are making sure that the PCA is calculated on the same data as we passed into the clustering algorithm.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb74"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb74-1"><a href="#cb74-1" aria-hidden="true" tabindex="-1"></a>pca_wine <span class="ot">&lt;-</span> df_wine <span class="sc">%&gt;%</span></span>
<span id="cb74-2"><a href="#cb74-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb74-3"><a href="#cb74-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale all numeric cols</span></span>
<span id="cb74-4"><a href="#cb74-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), scale)) <span class="sc">%&gt;%</span></span>
<span id="cb74-5"><a href="#cb74-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">prcomp</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s have a look. Since there is no missing data in this set we can easily use the original dataframe to color by wine type:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(pca_wine, <span class="at">data =</span> df_wine, <span class="at">color =</span> <span class="st">'Type'</span>,</span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">loadings =</span> <span class="cn">TRUE</span>, <span class="at">loadings.colour =</span> <span class="st">"grey30"</span>, </span>
<span id="cb75-3"><a href="#cb75-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">loadings.label.colour =</span> <span class="st">"black"</span>,</span>
<span id="cb75-4"><a href="#cb75-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">loadings.label =</span> <span class="cn">TRUE</span>, <span class="at">loadings.label.size =</span> <span class="fl">3.5</span>,</span>
<span id="cb75-5"><a href="#cb75-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">scale =</span> <span class="dv">0</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="presentation5_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Now we would like to add the cluster centriods to the plot. Just as a wine bottle with 13 dimensions has a certain PC1/PC2 coordinate, the centriod also does:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb76"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb76-1"><a href="#cb76-1" aria-hidden="true" tabindex="-1"></a><span class="co">#this is the first wine bottle in the set</span></span>
<span id="cb76-2"><a href="#cb76-2" aria-hidden="true" tabindex="-1"></a>df_wine[<span class="dv">1</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    Type Alcohol Malic  Ash Alcalinity Magnesium Phenols Flavanoids
1 Barolo   14.23  1.71 2.43       15.6       127     2.8       3.06
  Nonflavanoid Proanthocyanins Color  Hue Dilution Proline
1         0.28            2.29  5.64 1.04     3.92    1065</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="co">#this bottle is placed at -3.3/1.4 in the PCA plot</span></span>
<span id="cb78-2"><a href="#cb78-2" aria-hidden="true" tabindex="-1"></a>pca_wine<span class="sc">$</span>x[<span class="dv">1</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>        PC1         PC2         PC3         PC4         PC5         PC6 
-3.30742097 -1.43940225 -0.16527283 -0.21502463 -0.69109335 -0.22325037 
        PC7         PC8         PC9        PC10        PC11        PC12 
 0.59474883  0.06495586 -0.63963836 -1.01808396  0.45029317 -0.53928914 
       PC13 
 0.06605231 </code></pre>
</div>
</div>
<p>We can find the PC1/PC2 coordinates of cluster 1, 2 and 3 by putting their position in the original 13-dim space into the PCA object:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co">#project cluster centers from kmeans into the pca space</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a>centers_pca <span class="ot">&lt;-</span> <span class="fu">predict</span>(pca_wine, <span class="at">newdata =</span> kmeans_res<span class="sc">$</span>centers)</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>centers_pca</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         PC1        PC2         PC3         PC4        PC5         PC6
1 -1.0206234  0.8723669  1.09853134  0.60290901 -0.7830261  0.09575498
2 -2.3751274 -0.9408631 -0.32103480 -0.10604257  0.2867197 -0.19871649
3  2.7362113 -1.2107751 -0.17674684  0.07667507 -0.0919792  0.10663848
4  0.6113385  1.9464455 -0.09156296 -0.32666993  0.2305646  0.07159330
           PC7          PC8           PC9        PC10        PC11          PC12
1  0.186100194  0.136838314 -0.0104191856  0.13765106  0.09655731  0.0858676784
2 -0.008947737  0.005075841  0.0739699820 -0.06932845 -0.01239409 -0.0008655842
3 -0.072766741 -0.040644444  0.0002573087  0.05571503  0.00485592 -0.0042899679
4 -0.025425819 -0.047203159 -0.0858486648 -0.06004162 -0.04994390 -0.0476803079
         PC13
1  0.09281421
2 -0.04132451
3  0.06520735
4 -0.07732857</code></pre>
</div>
<div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a>kmeans_res<span class="sc">$</span>centers</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     Alcohol       Malic        Ash Alcalinity   Magnesium    Phenols
1 -0.7869073  0.04195151  0.2157781  0.3683284  0.43818899  0.6543578
2  0.9580555 -0.37748461  0.1969019 -0.8214121  0.39943022  0.9000233
3  0.1860184  0.90242582  0.2485092  0.5820616 -0.05049296 -0.9857762
4 -0.9051690 -0.53898599 -0.6498944  0.1592193 -0.71473842 -0.4537841
  Flavanoids Nonflavanoid Proanthocyanins      Color        Hue    Dilution
1  0.5746004   -0.5429201       0.8888549 -0.7346332  0.2830335  0.60628629
2  0.9848901   -0.6204018       0.5575193  0.2423047  0.4799084  0.76926636
3 -1.2327174    0.7148253      -0.7474990  0.9857177 -1.1879477 -1.29787850
4 -0.2408779    0.3315072      -0.4329238 -0.9177666  0.5202140  0.07869143
     Proline
1 -0.5169332
2  1.2184972
3 -0.3789756
4 -0.7820425</code></pre>
</div>
</div>
<p>Let’s make this into a dataframe and add labels:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="co">#project cluster centers from kmeans into the pca space</span></span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a>centers_pca <span class="ot">&lt;-</span> <span class="fu">predict</span>(pca_wine, <span class="at">newdata =</span> kmeans_res<span class="sc">$</span>centers) <span class="sc">%&gt;%</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb84-3"><a href="#cb84-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Label clusters</span></span>
<span id="cb84-4"><a href="#cb84-4" aria-hidden="true" tabindex="-1"></a>centers_pca<span class="sc">$</span>cluster <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(centers_pca))  </span>
<span id="cb84-5"><a href="#cb84-5" aria-hidden="true" tabindex="-1"></a>centers_pca</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         PC1        PC2         PC3         PC4        PC5         PC6
1 -1.0206234  0.8723669  1.09853134  0.60290901 -0.7830261  0.09575498
2 -2.3751274 -0.9408631 -0.32103480 -0.10604257  0.2867197 -0.19871649
3  2.7362113 -1.2107751 -0.17674684  0.07667507 -0.0919792  0.10663848
4  0.6113385  1.9464455 -0.09156296 -0.32666993  0.2305646  0.07159330
           PC7          PC8           PC9        PC10        PC11          PC12
1  0.186100194  0.136838314 -0.0104191856  0.13765106  0.09655731  0.0858676784
2 -0.008947737  0.005075841  0.0739699820 -0.06932845 -0.01239409 -0.0008655842
3 -0.072766741 -0.040644444  0.0002573087  0.05571503  0.00485592 -0.0042899679
4 -0.025425819 -0.047203159 -0.0858486648 -0.06004162 -0.04994390 -0.0476803079
         PC13 cluster
1  0.09281421       1
2 -0.04132451       2
3  0.06520735       3
4 -0.07732857       4</code></pre>
</div>
</div>
<p>Alright! The last step is to add these 4 points, one for each cluster, to the autoplot. Did you know you can add ggplot geoms to autoplots?</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(pca_wine, <span class="at">data =</span> df_wine, <span class="at">color =</span> <span class="st">'Type'</span>,</span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a>         <span class="at">loadings =</span> <span class="cn">TRUE</span>, <span class="at">loadings.colour =</span> <span class="st">"grey30"</span>, </span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">loadings.label.colour =</span> <span class="st">"black"</span>,</span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">loadings.label =</span> <span class="cn">TRUE</span>, <span class="at">loadings.label.size =</span> <span class="fl">3.5</span>,</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">scale =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Cluster centers</span></span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> centers_pca, <span class="fu">aes</span>(<span class="at">x =</span> PC1, <span class="at">y =</span> PC2, <span class="at">color =</span> cluster),</span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a>             <span class="at">shape =</span> <span class="dv">8</span>, <span class="at">size =</span> <span class="dv">6</span>, <span class="at">stroke =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="presentation5_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We are still coloring the PCA plot by the known wine type. Let’s switch it to instead display which cluster each bottle has been assigned to by k-means:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="co">#add cluster info to the dataframe</span></span>
<span id="cb87-2"><a href="#cb87-2" aria-hidden="true" tabindex="-1"></a>df_wine<span class="sc">$</span>Cluster <span class="ot">&lt;-</span> <span class="fu">factor</span>(kmeans_res<span class="sc">$</span>cluster)</span>
<span id="cb87-3"><a href="#cb87-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb87-4"><a href="#cb87-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(pca_wine, <span class="at">data =</span> df_wine, <span class="at">color =</span> <span class="st">'Cluster'</span>,</span>
<span id="cb87-5"><a href="#cb87-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">loadings =</span> <span class="cn">TRUE</span>, <span class="at">loadings.colour =</span> <span class="st">"grey30"</span>, </span>
<span id="cb87-6"><a href="#cb87-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">loadings.label.colour =</span> <span class="st">"black"</span>,</span>
<span id="cb87-7"><a href="#cb87-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">loadings.label =</span> <span class="cn">TRUE</span>, <span class="at">loadings.label.size =</span> <span class="fl">3.5</span>,</span>
<span id="cb87-8"><a href="#cb87-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">scale =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb87-9"><a href="#cb87-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Cluster centers</span></span>
<span id="cb87-10"><a href="#cb87-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> centers_pca, <span class="fu">aes</span>(<span class="at">x =</span> PC1, <span class="at">y =</span> PC2, <span class="at">color =</span> cluster),</span>
<span id="cb87-11"><a href="#cb87-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">shape =</span> <span class="dv">8</span>, <span class="at">size =</span> <span class="dv">6</span>, <span class="at">stroke =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="presentation5_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Well the centroids are in the middle of their respective clusters but this does not look ideal. Perhaps 4 is not the best number of clusters for this dataset.</p>
</section>
<section id="optimal-number-of-clusters" class="level3">
<h3 class="anchored" data-anchor-id="optimal-number-of-clusters">Optimal number of clusters</h3>
<p>There are several ways to investigate the ideal number of clusters and <code>fviz_nbclust</code> from the factoextra package provides three of them:</p>
<p>The so-called elbow method observes how the sum of squared errors (sse) changes as we vary the number of clusters. This is also sometimes referred to as “within sum of square” (wss).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(factoextra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Welcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa</code></pre>
</div>
<div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>df_wine <span class="sc">%&gt;%</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb90-3"><a href="#cb90-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale all numeric cols</span></span>
<span id="cb90-4"><a href="#cb90-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), scale)) <span class="sc">%&gt;%</span></span>
<span id="cb90-5"><a href="#cb90-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fviz_nbclust</span>(kmeans, <span class="at">method =</span> <span class="st">"wss"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="presentation5_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The silhouette coefficient is a measure of cluster cohesion and separation. It quantifies how well a data point fits into its assigned cluster, by looking at how close it is to other points in its cluster and how far from points of other clusters. You need to have at least 2 clusters for the silhouette coefficient to be defined.</p>
<p>Unlike the elbow of the sums of square errors, the silhouette score is supposed to peak:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a>df_wine <span class="sc">%&gt;%</span></span>
<span id="cb91-2"><a href="#cb91-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb91-3"><a href="#cb91-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale all numeric cols</span></span>
<span id="cb91-4"><a href="#cb91-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), scale)) <span class="sc">%&gt;%</span></span>
<span id="cb91-5"><a href="#cb91-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fviz_nbclust</span>(kmeans, <span class="at">method =</span> <span class="st">"silhouette"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="presentation5_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>The gap statistic compares the within-cluster variation (how compact the clusters are) for different values of K to the expected variation under a null reference distribution (i.e., random clustering).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>df_wine <span class="sc">%&gt;%</span></span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb92-3"><a href="#cb92-3" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale all numeric cols</span></span>
<span id="cb92-4"><a href="#cb92-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), scale)) <span class="sc">%&gt;%</span></span>
<span id="cb92-5"><a href="#cb92-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">fviz_nbclust</span>(kmeans, <span class="at">method =</span> <span class="st">"gap_stat"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="presentation5_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>All three of them tell us there should be three clusters and we also know there are three cultivars of wine in the dataset. Let’s redo k-means with three centroids.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed to ensure reproducibility</span></span>
<span id="cb93-2"><a href="#cb93-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)  </span>
<span id="cb93-3"><a href="#cb93-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-4"><a href="#cb93-4" aria-hidden="true" tabindex="-1"></a><span class="co">#run kmeans</span></span>
<span id="cb93-5"><a href="#cb93-5" aria-hidden="true" tabindex="-1"></a>kmeans_res <span class="ot">&lt;-</span> df_wine <span class="sc">%&gt;%</span></span>
<span id="cb93-6"><a href="#cb93-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.numeric)) <span class="sc">%&gt;%</span></span>
<span id="cb93-7"><a href="#cb93-7" aria-hidden="true" tabindex="-1"></a>  <span class="co">#scale all numeric cols</span></span>
<span id="cb93-8"><a href="#cb93-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="fu">across</span>(<span class="fu">where</span>(is.numeric), scale)) <span class="sc">%&gt;%</span></span>
<span id="cb93-9"><a href="#cb93-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">kmeans</span>(<span class="at">centers =</span> <span class="dv">3</span>, <span class="at">nstart =</span> <span class="dv">25</span>)</span>
<span id="cb93-10"><a href="#cb93-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb93-11"><a href="#cb93-11" aria-hidden="true" tabindex="-1"></a><span class="co">#project cluster centers from kmeans into the pca space</span></span>
<span id="cb93-12"><a href="#cb93-12" aria-hidden="true" tabindex="-1"></a>centers_pca <span class="ot">&lt;-</span> <span class="fu">predict</span>(pca_wine, <span class="at">newdata =</span> kmeans_res<span class="sc">$</span>centers) <span class="sc">%&gt;%</span> <span class="fu">as.data.frame</span>()</span>
<span id="cb93-13"><a href="#cb93-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Label clusters</span></span>
<span id="cb93-14"><a href="#cb93-14" aria-hidden="true" tabindex="-1"></a>centers_pca<span class="sc">$</span>cluster <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(centers_pca))</span>
<span id="cb93-15"><a href="#cb93-15" aria-hidden="true" tabindex="-1"></a>centers_pca</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>          PC1        PC2          PC3         PC4         PC5         PC6
1  2.71238444 -1.1224849 -0.238420685  0.06228125 -0.07346875  0.09964414
2 -2.26979079 -0.9294322  0.001523733 -0.13511700  0.13453261 -0.21766922
3  0.03685265  1.7672542  0.185615130  0.08001400 -0.07067870  0.12944063
           PC7          PC8         PC9        PC10         PC11         PC12
1 -0.060213318 -0.007367207 -0.01997059  0.06129547  0.008093155  0.003445464
2  0.051963343  0.024894027  0.05014407 -0.07446923 -0.021230820 -0.007417378
3 -0.002320739 -0.017964647 -0.03216049  0.02293882  0.013900922  0.004371673
          PC13 cluster
1  0.050408713       1
2 -0.050476861       2
3  0.008595707       3</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="co">#add updated cluster info to the dataframe</span></span>
<span id="cb95-2"><a href="#cb95-2" aria-hidden="true" tabindex="-1"></a>df_wine<span class="sc">$</span>Cluster <span class="ot">&lt;-</span> <span class="fu">factor</span>(kmeans_res<span class="sc">$</span>cluster)</span>
<span id="cb95-3"><a href="#cb95-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb95-4"><a href="#cb95-4" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(pca_wine, <span class="at">data =</span> df_wine, <span class="at">color =</span> <span class="st">'Cluster'</span>,</span>
<span id="cb95-5"><a href="#cb95-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">loadings =</span> <span class="cn">TRUE</span>, <span class="at">loadings.colour =</span> <span class="st">"grey30"</span>, </span>
<span id="cb95-6"><a href="#cb95-6" aria-hidden="true" tabindex="-1"></a>         <span class="at">loadings.label.colour =</span> <span class="st">"black"</span>,</span>
<span id="cb95-7"><a href="#cb95-7" aria-hidden="true" tabindex="-1"></a>         <span class="at">loadings.label =</span> <span class="cn">TRUE</span>, <span class="at">loadings.label.size =</span> <span class="fl">3.5</span>,</span>
<span id="cb95-8"><a href="#cb95-8" aria-hidden="true" tabindex="-1"></a>         <span class="at">scale =</span> <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb95-9"><a href="#cb95-9" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Cluster centers</span></span>
<span id="cb95-10"><a href="#cb95-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> centers_pca, <span class="fu">aes</span>(<span class="at">x =</span> PC1, <span class="at">y =</span> PC2, <span class="at">color =</span> cluster),</span>
<span id="cb95-11"><a href="#cb95-11" aria-hidden="true" tabindex="-1"></a>             <span class="at">shape =</span> <span class="dv">8</span>, <span class="at">size =</span> <span class="dv">6</span>, <span class="at">stroke =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="presentation5_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Indeed this looks better!</p>
<p>That concludes our foray into modelling for now and it’s time for the exercise.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>